name: helm
arch: ${ARCH}
platform: linux
version: ${VERSION}
release: 1
maintainer: Simon Lauger <simon@lauger.de>
description: The Kubernetes Package Manager
vendor: Helm Authors
homepage: https://helm.sh
license: Apache-2.0

contents:
  - src: ./bin/helm
    dst: /usr/local/bin/helm
    file_info:
      mode: 0755
